const dialogues = [
    { dialogue: "Mogambo khush hua!", movie: "Mr. India" },
    { dialogue: "Kitne aadmi the?", movie: "Sholay" },
    { dialogue: "Basanti, in kutto ke samne mat nachna.", movie: "Sholay" },
    { dialogue: "Don ka intezaar toh gyarah mulkon ki police kar rahi hai.", movie: "Don" },
    { dialogue: "Dosti ka ek usool hai madam: no sorry, no thank you.", movie: "Maine Pyar Kiya" },
    { dialogue: "Aaj khush to bahut hoge tum.", movie: "Hera Pheri" },
    { dialogue: "Aap purush hi nahi, maha purush hai!", movie: "Chupke Chupke" },
    { dialogue: "Babu Moshai Zindagi Badi Haseen Hai.", movie: "Anand" },
    { dialogue: "Jab tak hai jaan, main nachunga!", movie: "Dilwale Dulhania Le Jayenge" },
    { dialogue: "Padhne likhne ka shauk tha, isliye engineer ban gaya.", movie: "3 Idiots" },
    { dialogue: "Bhai, tumhara naam kya hai, Kallu Mama?", movie: "Gully Boy" },
    { dialogue: "Keh diya na, bas keh diya.", movie: "Dilwale" },
    { dialogue: "Agar tum mujhe paagal kahoge, toh main paagal ho jaaunga!", movie: "Dil Chahta Hai" },
    { dialogue: "I am a Rockstar.", movie: "Rockstar" },
    { dialogue: "Pehle use baat karni seekh, phir teri shaadi karenge.", movie: "Jab We Met" },
    { dialogue: "Yeh jo zindagi ka paheli hai, yeh kisi ko samajh nahi aata.", movie: "Barfi" },
    { dialogue: "Tumse na ho payega.", movie: "Zindagi Na Milegi Dobara" },
    { dialogue: "Pehle use pyaar karna sikho, phir apne aap ko samjha lo.", movie: "Dil Dhadakne Do" },
    { dialogue: "Duniya mein sabse zaruri cheez pyaar hai.", movie: "Dilwale Dulhania Le Jayenge" },
    { dialogue: "Main kya karoon, jo hona tha, ho gaya!", movie: "Kabhi Alvida Naa Kehna" },
    { dialogue: "Bapu, woh dhamaal karna hai!", movie: "Dhamaal" },
    { dialogue: "Kuch kuch hota hai, Rahul, tum nahi samjhoge.", movie: "Kuch Kuch Hota Hai" },
    { dialogue: "Mujhe gussa mat dilao!", movie: "Singham" },
    { dialogue: "Kyunki har koi khud ka dard samajhta hai.", movie: "Meri Pyaari Bindu" },
    { dialogue: "Mujhe yeh kehna hai ki, aaj bhi tum mere dil mein ho.", movie: "Kabir Singh" },
    { dialogue: "Agar hum kisi ke liye jeet rahe hain, toh kis liye jeet rahe hain?", movie: "Lagaan" },
    { dialogue: "Tu hai ki nahi!", movie: "Dabangg" },
    { dialogue: "Bhaiyya, tumne humare dimaag ka naal bandha hai!", movie: "Phir Hera Pheri" },
    { dialogue: "Tension lene ka nahi, sirf dene ka.", movie: "Chup Chup Ke" },
    { dialogue: "Jab tak hai jaan, main nachunga!", movie: "Dilwale Dulhania Le Jayenge" },
    { dialogue: "Mujhe yeh jo dard hota hai, yeh kabhi nahi khatam hota.", movie: "Tamasha" },
    { dialogue: "Mujhse pyaar karna hai toh baar baar kehna padega.", movie: "Raat Baaki" },
    { dialogue: "Toh kaunsa asli hai, aur kaunsa fake?", movie: "War" },
    { dialogue: "Tumhare piche jo bhi ladki gayi, woh tumse nafrat kar rahi hogi!", movie: "Hera Pheri" },
    { dialogue: "Apna time aayega!", movie: "Gully Boy" },
    { dialogue: "Har shaam ki roshni se pyaar karo, jo bhi milta hai, woh dekh ke chalo.", movie: "Bajirao Mastani" },
    { dialogue: "Life mein jo bhi decision lena hai, apni marzi se lena.", movie: "Zindagi Na Milegi Dobara" },
    { dialogue: "Duniya mein sabse zaroori cheez pyaar hai.", movie: "Dilwale Dulhania Le Jayenge" },
    { dialogue: "Mera naam hai Raees, aur main apne dosto ki yaari ke liye jaan de sakta hoon.", movie: "Raees" },
    { dialogue: "Main apni favorite hoon.", movie: "Jab We Met" },
    { dialogue: "Jab hum usse dekhenge, tab humein apni zindagi ka asli mazaa milega.", movie: "Bajrangi Bhaijaan" },
    { dialogue: "Agar tumhe zindagi ke baare mein sach jaana hai, toh apne dil se baat karo.", movie: "Kabhi Khushi Kabhie Gham" },
    { dialogue: "Mujhse shaadi karogi?", movie: "Dilwale Dulhania Le Jayenge" },
    { dialogue: "Mera naam Raj hai, aur main ameer hoon.", movie: "Dilwale Dulhania Le Jayenge" },
    { dialogue: "Dil karne ko toh kuch bhi kar sakte hain, bas pehchaan hona zaroori hai.", movie: "Baahubali" },
    { dialogue: "Meri ek bat samajh, tujhse dosti karna sabse badi baat hai.", movie: "Dosti" },
    { dialogue: "Hum log dil se judte hain!", movie: "Dil Chahta Hai" },
    { dialogue: "Tum logon ka attitude mujhe thoda achha lagta hai.", movie: "Bajrangi Bhaijaan" },
    { dialogue: "Ek baar jo maine commitment kar di, toh main khud ki bhi nahi sunta.", movie: "Wanted" },
    { dialogue: "Meri zindagi main jo bhi ho raha hai, woh mere khud ke decisions ka natija hai.", movie: "Tamasha" },
    { dialogue: "Zindagi ka har pal important hai, har pal jeena hai!", movie: "Dilwale" },
    { dialogue: "Yeh dil maange more!", movie: "Tanu Weds Manu" },
    { dialogue: "Dil se kaam lo, toh sab kuch ho sakta hai!", movie: "Dil Se" },
    { dialogue: "Har aadmi apne ghar ka hero hota hai.", movie: "Hera Pheri" },
    { dialogue: "Mujhe apni jaan ki padi hai.", movie: "Singham" },
    { dialogue: "Pyaar kiya toh darna kya?", movie: "Mughal-e-Azam" },
    { dialogue: "Jab tum kisi ka pyaar jeet lo, toh uska dil jeet lo!", movie: "Maine Pyaar Kiya" },
    { dialogue: "Kabhi bhi apne aap ko underestimate mat karna.", movie: "Chhichhore" },
    { dialogue: "Agar yeh pyaar ka game hai, toh main jeetne ki koshish karunga!", movie: "Tanu Weds Manu" },
    { dialogue: "Dil toh bachcha hai ji!", movie: "Ishqiya" },
    { dialogue: "Mujhe laga koi pyaar karega, lekin tumne jo kiya woh sabko hila dene wala tha.", movie: "Barfi" },
    { dialogue: "Humne jo bhi kiya, apne liye kiya!", movie: "Jab We Met" },
    { dialogue: "Dil mein kuch hai jo bol nahi sakte!", movie: "Kabir Singh" },
    { dialogue: "Mere baare mein mat soch, bas apne baare mein soch!", movie: "Gully Boy" },
    { dialogue: "Hum dil se soch kar karte hain!", movie: "Dilwale" },
    { dialogue: "Mujhe kuch alag karna hai!", movie: "Rockstar" },
    { dialogue: "Kyunki aaj jo tumne kiya, woh baad mein hamesha yaad rahega.", movie: "Kabir Singh" },
    { dialogue: "Pyaar ka ek secret hai: uska imaan aur ikhlaas sabse zaroori hai.", movie: "Prem Ratan Dhan Payo" },
    { dialogue: "Aaj jo ho raha hai, woh apni zindagi ka ek hissa hai.", movie: "Zindagi Na Milegi Dobara" },
    { dialogue: "Kyunki sab kuch ruk gaya hai, sirf pyaar ke chakkar mein.", movie: "Maine Pyaar Kiya" },
    { dialogue: "Humein kuch aise zindagi jeeni hai, jo humesha yaad rahe.", movie: "Dilwale" },
    { dialogue: "Bhi kehte hain na, duniya mein sabse badi baat apni zindagi ka sach samajhna hai!", movie: "Hera Pheri" },
    { dialogue: "Dilwale ho ya dil se, sabhi ko apni zindagi apne tarike se jeeni chahiye.", movie: "Dilwale" }
];

export default dialogues;
